version: '3.9'
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: autosite
      POSTGRES_USER: devusr
      POSTGRES_PASSWORD: devpwd
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  api:
    build:
      context: ./backend
      target: prod
    env_file:
      - ./backend/.env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: devusr
      DB_PASSWORD: devpwd
      DB_NAME: autosite
      PORT: 3000
      PUBLIC_UPLOAD_BASE_URL: http://frontend/uploads
    depends_on:
      - db
    expose:
      - "3000"
    volumes:
      - ./uploads:/app/uploads

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    depends_on:
      - api
    ports:
      - "5500:80"
    volumes:
      - ./uploads:/usr/share/nginx/html/uploads

volumes:
  pg_data: {}

