version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: autosite-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: autosite
      POSTGRES_USER: devusr
      POSTGRES_PASSWORD: devpwd
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devusr -d autosite"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./backend
      target: prod
    container_name: autosite-api
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: devusr
      DB_PASSWORD: devpwd
      DB_NAME: autosite
      PORT: 3000
      PUBLIC_UPLOAD_BASE_URL: http://frontend/uploads
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "3000"
    volumes:
      - ./uploads:/app/uploads

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: autosite-frontend
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "5500:80"
    volumes:
      - ./uploads:/usr/share/nginx/html/uploads

volumes:
  pg_data:
